#BELOW PANDA CAN BE COMMENTED OUT
#panda:                    #useful if you use a namespace for the robot
    # Publish joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    panda_arm_controller:
        type: effort_controllers/JointEffortController

        joint: panda_joint1
        pid: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }

        joint: panda_joint2
        pid: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }

        joint: panda_joint3
        pid: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }

        joint: panda_joint4
        pid: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }

        joint: panda_joint5
        pid: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }

        joint: panda_joint6
        pid: { p: 7000, d: 50, i: 0.01, i_clamp: 1 }

        joint: panda_joint7
        pid: { p: 2000, d: 20, i: 0.0, i_clamp: 1 }


    panda_hand_controller:
        type: effort_controllers/JointEffortController
        joint: panda_finger_joint1
        pid: { p: 5, d: 3.0, i: 0, i_clamp: 1 }

        joint: panda_finger_joint2
        pid: { p: 5, d: 1.0, i: 0, i_clamp: 1 }

